# Generated by Django 2.0.2 on 2018-02-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scrap',
            fields=[
                ('scrap_id', models.AutoField(primary_key=True, serialize=False)),
                ('scrap_url', models.CharField(max_length=300)),
                ('scrap_title', models.CharField(max_length=300)),
                ('scrap_content', models.TextField()),
            ],
        ),
    ]
